feat(nocohub): Disabled backend wait temporarily

diff --git a/.github/workflows/playwright-test-workflow.yml b/.github/workflows/playwright-test-workflow.yml
--- a/.github/workflows/playwright-test-workflow.yml
+++ b/.github/workflows/playwright-test-workflow.yml
@@ -100,12 +100,12 @@ jobs:
       # - name: Install Playwright Browsers
       #   working-directory: ./tests/playwright
       #   run: npx playwright install chromium --with-deps
-      - name: Wait for backend
-        run: |
-          while ! curl --output /dev/null --silent --head --fail http://localhost:8080; do
-            printf '.'
-            sleep 2
-          done
+      # - name: Wait for backend
+      #   run: |
+      #     while ! curl --output /dev/null --silent --head --fail http://localhost:8080; do
+      #       printf '.'
+      #       sleep 2
+      #     done
 
       - name: Run Playwright tests
         working-directory: ./tests/playwright
