refactor: revert
Signed-off-by: Pranav C <pranavxc@gmail.com>

feat: shared base

Signed-off-by: Pranav C <pranavxc@gmail.com>

fix: remove duplicate import statement

Signed-off-by: Pranav C <pranavxc@gmail.com>

fix: disable starred & license menu

Signed-off-by: Raju Udava <86527202+dstala@users.noreply.github.com>

test: fix airtable wait issue

Signed-off-by: Raju Udava <86527202+dstala@users.noreply.github.com>

test: enable mysql in ci

Signed-off-by: Raju Udava <86527202+dstala@users.noreply.github.com>

test: fix checkbox order for sqlite

Signed-off-by: Raju Udava <86527202+dstala@users.noreply.github.com>

test: disable quick tests

Signed-off-by: Raju Udava <86527202+dstala@users.noreply.github.com>

test: fix dbType env variable for CI

Signed-off-by: Raju Udava <86527202+dstala@users.noreply.github.com>

test: workspace API access error fix

Signed-off-by: Raju Udava <86527202+dstala@users.noreply.github.com>

test: enable SQLite CI CD

Signed-off-by: Raju Udava <86527202+dstala@users.noreply.github.com>

test: use DB_TYPE env variable

Signed-off-by: Raju Udava <86527202+dstala@users.noreply.github.com>

test: enable SQLite UT

Signed-off-by: Raju Udava <86527202+dstala@users.noreply.github.com>

test: isHub cleanup

Signed-off-by: Raju Udava <86527202+dstala@users.noreply.github.com>

test: add check for EE Timezone spec

Signed-off-by: Raju Udava <86527202+dstala@users.noreply.github.com>

chore: cleanup

Signed-off-by: Pranav C <pranavxc@gmail.com>

chore: cleanup

Signed-off-by: Pranav C <pranavxc@gmail.com>

test: EE check fix

Signed-off-by: Raju Udava <86527202+dstala@users.noreply.github.com>

chore: test correction

Signed-off-by: Pranav C <pranavxc@gmail.com>

chore: sync latest changes

Signed-off-by: Pranav C <pranavxc@gmail.com>

test: set EE=false

Signed-off-by: Raju Udava <86527202+dstala@users.noreply.github.com>

test: set NC Edition to community in workflow file

Signed-off-by: Raju Udava <86527202+dstala@users.noreply.github.com>

chore: update sdk build command

Signed-off-by: Pranav C <pranavxc@gmail.com>

refactor: i18n and other changes

Signed-off-by: Pranav C <pranavxc@gmail.com>

feat: new ui

Signed-off-by: Pranav C <pranavxc@gmail.com>

diff --git a/.github/workflows/playwright-test-workflow.yml b/.github/workflows/playwright-test-workflow.yml
--- a/.github/workflows/playwright-test-workflow.yml
+++ b/.github/workflows/playwright-test-workflow.yml
@@ -47,6 +47,10 @@ jobs:
             ${{ runner.os }}-build-${{ env.cache-name }}-
             ${{ runner.os }}-build-
             ${{ runner.os }}-
+      - name: Set CI env
+        run: export CI=true
+      - name: Set NC Edition
+        run: export EE=true
       - name: install dependencies nocodb-sdk
         working-directory: ./packages/nocodb-sdk
         run: npm install
@@ -119,28 +123,28 @@ jobs:
         working-directory: ./tests/playwright
         run: E2E_DB_TYPE=${{ inputs.db }} node ./scripts/stressTestNewlyAddedTest.js
 
-      # Quick tests (pg on sqlite shard 0 and sqlite on sqlite shard 1)
-      - name: Run quick server and tests (pg)
-        if: ${{ inputs.db == 'sqlite' && inputs.shard == '1' }}
-        working-directory: ./packages/nocodb
-        run: |
-          kill -9 $(lsof -t -i:8080)
-          npm run watch:run:playwright:pg:cyquick &
-      - name: Run quick server and tests (sqlite)
-        if: ${{ inputs.db == 'sqlite' && inputs.shard == '2' }}
-        working-directory: ./packages/nocodb
-        run: |
-          kill -9 $(lsof -t -i:8080)
-          npm run watch:run:playwright:quick > quick_${{ inputs.shard }}_test_backend.log &
-      - name: Wait for backend & run quick tests
-        if: ${{ inputs.db == 'sqlite' }}
-        working-directory: ./tests/playwright
-        run: |
-          while ! curl --output /dev/null --silent --head --fail http://localhost:8080; do
-            printf '.'
-            sleep 2
-          done
-          PLAYWRIGHT_HTML_REPORT=playwright-report-quick npm run test:quick
+#      # Quick tests (pg on sqlite shard 0 and sqlite on sqlite shard 1)
+#      - name: Run quick server and tests (pg)
+#        if: ${{ inputs.db == 'sqlite' && inputs.shard == '1' }}
+#        working-directory: ./packages/nocodb
+#        run: |
+#          kill -9 $(lsof -t -i:8080)
+#          npm run watch:run:playwright:pg:cyquick &
+#      - name: Run quick server and tests (sqlite)
+#        if: ${{ inputs.db == 'sqlite' && inputs.shard == '2' }}
+#        working-directory: ./packages/nocodb
+#        run: |
+#          kill -9 $(lsof -t -i:8080)
+#          npm run watch:run:playwright:quick > quick_${{ inputs.shard }}_test_backend.log &
+#      - name: Wait for backend & run quick tests
+#        if: ${{ inputs.db == 'sqlite' }}
+#        working-directory: ./tests/playwright
+#        run: |
+#          while ! curl --output /dev/null --silent --head --fail http://localhost:8080; do
+#            printf '.'
+#            sleep 2
+#          done
+#          PLAYWRIGHT_HTML_REPORT=playwright-report-quick npm run test:quick
       - uses: actions/upload-artifact@v3
         if: ${{ inputs.db == 'sqlite' }}
         with:
